### PR TITLE
French version of pages+pdf

### PR DESCRIPTION
**Pull request by tristanbo**
• plain FR translation from EN original
• I put centimeters in pole position
• I reduced the file size straight in the pages doc for github upload (< 25mb)

thanks for this very clever mask template.   I did several and built upon it. will follow up.

### CODE REVIEW

**Comment by lorenbrichter** [comment]
This is fantastic, thank you!

**Comment by tristanbo** [comment]
Hi there, 

I’m celebrating my 20th mask, and I keep you updated on what is becoming a ‘fork'

Some context: 
The “right angle base” of the ragmask remains its most clever aspect, and it’s a breeze to build upon the template.
I did quite a series of ragmasks last weeks : 80% ragmask + 20% finetuning/esthetics (I’m doing this in Belgium/Switzerland, supply is rather OK, my goal is now to facilitate mainstream use). I’m about to make 40 more masks tomorrow for the workers @ my office.

Here are the main differences in my “Belgian fork”:
	• swiffer antistatic cloths (as filters) are 27cm wide here. I narrowed the template to 27cm instead of 28cm		
	• I “tear” fabric into rectangle instead of cutting (it’s faster and makes no difference afterwards)
	• I make adjustments of the face shape for each person, on request (super easy with the ragmask template, even after it’s finished)
	• I use different cloths from inside/outside (basically just 1 more seam.. and bang, it becomes something you happily wear in the streets, all day)
	• I use 2 looped straps instead of 4 separate straps (see picture)

The last one is straightforward  and could apply to the “roots ragmask”

Let me know if/how you see anything worth implementing in the git.

+T

**Comment by lorenbrichter** [comment]
This is fantastic! I'm super excited you're making changes. @Its-Gardner has been going down a similar path, modifying the profile for a better final fit.

That's a clever point, the fact that you can basically "tailor" the mask after it's been made isn't something I had considered before.

We started work on v3, which I think will change the "default" profile slightly (more straight cuts, faster/simpler) to make, plus will add one step flipping inside out after the first stitch to eliminate the last raw edge. Since we're transitioning from "make as many masks for medical workers as fast as possible" to more "make masks for regular people that need to survive many washing cycles", I think adding a step to make the finished mask cleaner is worth it.

Photo didn't come through in your last message but would love to see how you did the single looped strap.

**Comment by tristanbo** [comment]
• It was inspiring to see you exploring topological changes for breathing.  I wanted to start from the rectangular pattern and achieve similar volume/structure.

• I uploaded this - with other notes - in the  “3.0 suggestions” thread  (mostly about straps, wire, breathability) - https://github.com/lorenbrichter/ragmask/issues/8

**Pull request merged**
