### PR TITLE
French Translation Edits

### PR DESCRIPTION
**Pull request by alexandresitbon**
1. Deleted French pages.app file v2.2
2. Uploaded French pages.app file v2.3b2 based on English v2.3b2
3. Deleted ragmask_fr.pdf v2.2
4. Uploaded ragmask_fr.pdf based on French pages.app file v2.3b2

### CODE REVIEW

**Comment by lorenbrichter** [comment]
Thank you so much! It looks like there may have been a goof somewhere along the lines, I'm taking a look at the updated Pages file and somehow the image quality got reduced. (The Pages file should be ~27MB, it's ~3 in here). If you're not sure how it happened (and it's not super trivial to fix), just let me know and I'll drop the translated text back together with the original photos.

**Comment by alexandresitbon** [comment]
@lorenbrichter My bad! I actually don't think it came from me. Took a screenshot of your repo and ragmask_2.2_fr.pages is 3.1MB. This is the file I started from. I will fix mine by taking pictures from ragmask_2.3.pages.
Screen Shot 2020-04-12 at 9 35 45 AM

**Comment by lorenbrichter** [comment]
Doh, that was probably from the first translation and I never noticed the first time! Sorry!

**Comment by alexandresitbon** [comment]
No worries! Just fixed the pages file. Before I re-upload, what would you like me to do with the size of the pdf file? Now that pages is 28.7 MB, my pdf is 23MB however yours is 3.09 MB.

**Comment by lorenbrichter** [comment]
I've been running them through this at 90% quality:

https://tools.pdf24.org/en/compress-pdf#s=1585782995305

**Comment by alexandresitbon** [comment]
Great. Thanks for the link. Both files are now fixed. I've re-uploaded the pdf file but GitHub won't let me upload the large pages file. See error message attached.
Screen Shot 2020-04-12 at 10 53 50 AM

**Comment by lorenbrichter** [comment]
Thank you! Gah, that stinks. Could you just email over to translations@ragmask.com ?

**Comment by alexandresitbon** [comment]
Done. Let me know if you need help with anything else!

**Pull request merged**
